# Generated by Django 5.2.12 on 2026-08-22 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("area_juridica", models.CharField(blank=True, max_length=120)),
                (
                    "canal_sugerido",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("blog", "Blog"),
                            ("email", "E-mail"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("atrair_clientes", "Atrair potenciais clientes"),
                            ("autoridade", "Construir autoridade"),
                            ("educar", "Educar audiência"),
                            ("relacionamento", "Relacionamento"),
                            ("trafego", "Tráfego para site/blog"),
                            ("marca", "Fortalecer marca"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("usada", "Usada"),
                            ("descartada", "Descartada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_marketing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideia de conteúdo",
                "verbose_name_plural": "Ideias de conteúdo",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("tema", models.CharField(blank=True, max_length=255)),
                ("area_juridica", models.CharField(blank=True, max_length=120)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("blog", "Blog"),
                            ("email", "E-mail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("formato", models.CharField(blank=True, max_length=40)),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("atrair_clientes", "Atrair potenciais clientes"),
                            ("autoridade", "Construir autoridade"),
                            ("educar", "Educar audiência"),
                            ("relacionamento", "Relacionamento"),
                            ("trafego", "Tráfego para site/blog"),
                            ("marca", "Fortalecer marca"),
                        ],
                        max_length=30,
                    ),
                ),
                ("publico", models.CharField(blank=True, max_length=200)),
                ("palavra_chave", models.CharField(blank=True, max_length=120)),
                (
                    "tom",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("educativo", "Educativo"),
                            ("profissional", "Profissional"),
                            ("didatico", "Didático"),
                            ("institucional", "Institucional"),
                            ("autoridade", "Autoridade"),
                        ],
                        default="profissional",
                        max_length=20,
                    ),
                ),
                ("cta", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ideia", "Ideia"),
                            ("rascunho", "Rascunho"),
                            ("gerado_ia", "Gerado por IA"),
                            ("em_revisao", "Em revisão"),
                            ("aprovado", "Aprovado"),
                            ("agendado", "Agendado"),
                            ("publicado", "Publicado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("data_planejada", models.DateField(blank=True, null=True)),
                ("corpo", models.TextField(blank=True)),
                ("metadados", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derivados",
                        to="marketing.contentitem",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conteudos_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_marketing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo",
                "verbose_name_plural": "Conteúdos",
                "ordering": ["-atualizado_em"],
            },
        ),
        migrations.CreateModel(
            name="ContentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visualizacoes", models.PositiveIntegerField(blank=True, null=True)),
                ("alcance", models.PositiveIntegerField(blank=True, null=True)),
                ("engajamento", models.PositiveIntegerField(blank=True, null=True)),
                ("cliques", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "leads_atribuidos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="marketing.contentitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desempenho de conteúdo",
                "verbose_name_plural": "Desempenhos de conteúdo",
            },
        ),
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("corpo_estruturado", models.JSONField(blank=True, default=dict)),
                ("corpo_texto", models.TextField(blank=True)),
                ("gerado_por_ia", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes",
                        to="marketing.contentitem",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versoes_conteudo_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão de conteúdo",
                "verbose_name_plural": "Versões de conteúdo",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="ContentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checklist", models.JSONField(blank=True, default=list)),
                ("observacoes", models.TextField(blank=True)),
                ("revisado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes_conteudo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprovacoes",
                        to="marketing.contentitem",
                    ),
                ),
                (
                    "content_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprovacoes",
                        to="marketing.contentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisão de conteúdo",
                "verbose_name_plural": "Revisões de conteúdo",
                "ordering": ["-revisado_em"],
            },
        ),
        migrations.CreateModel(
            name="EditorialCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("area_juridica", models.CharField(blank=True, max_length=120)),
                ("publico", models.CharField(blank=True, max_length=200)),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("atrair_clientes", "Atrair potenciais clientes"),
                            ("autoridade", "Construir autoridade"),
                            ("educar", "Educar audiência"),
                            ("relacionamento", "Relacionamento"),
                            ("trafego", "Tráfego para site/blog"),
                            ("marca", "Fortalecer marca"),
                        ],
                        max_length=30,
                    ),
                ),
                ("periodo_dias", models.PositiveSmallIntegerField(default=30)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("canais", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_marketing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendário editorial",
                "verbose_name_plural": "Calendários editoriais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="contentitem",
            name="calendario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens",
                to="marketing.editorialcalendar",
            ),
        ),
        migrations.CreateModel(
            name="ContentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_escritorio", models.CharField(blank=True, max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "areas_atuacao",
                    models.TextField(
                        blank=True, help_text="Uma área jurídica por linha."
                    ),
                ),
                ("publico", models.TextField(blank=True)),
                ("regiao", models.CharField(blank=True, max_length=120)),
                (
                    "tom_voz",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("educativo", "Educativo"),
                            ("profissional", "Profissional"),
                            ("didatico", "Didático"),
                            ("institucional", "Institucional"),
                            ("autoridade", "Autoridade"),
                        ],
                        default="profissional",
                        max_length=20,
                    ),
                ),
                ("diferenciais", models.TextField(blank=True)),
                ("palavras_preferidas", models.TextField(blank=True)),
                ("palavras_evitar", models.TextField(blank=True)),
                ("ctas_permitidas", models.TextField(blank=True)),
                ("observacoes_institucionais", models.TextField(blank=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_marketing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de conteúdo",
                "verbose_name_plural": "Perfis de conteúdo",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario",), name="marketing_unique_profile_per_user"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.UniqueConstraint(
                fields=("content_item", "numero"),
                name="marketing_unique_version_per_item",
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["usuario", "status"], name="marketing_c_usuario_2c8e24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["usuario", "data_planejada"],
                name="marketing_c_usuario_d0d370_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["usuario", "canal"], name="marketing_c_usuario_108097_idx"
            ),
        ),
    ]
