# Generated by Django 5.2.12 on 2026-08-22 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingIntegracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("google_analytics", "Google Analytics"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nao_conectado", "Não conectado"),
                            ("pendente", "Pendente"),
                            ("conectado", "Conectado"),
                        ],
                        default="nao_conectado",
                        max_length=20,
                    ),
                ),
                ("metadados", models.JSONField(blank=True, default=dict)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_marketing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integração de marketing",
                "verbose_name_plural": "Integrações de marketing",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "plataforma"),
                        name="marketing_unique_integracao_por_plataforma",
                    )
                ],
            },
        ),
    ]
