# Generated by Django 5.2.12

import django.db.models.deletion
from django.db import migrations, models

from organizacoes.backfill import organization_id_from_unique_active_membership

CONCRETE = (
    "ContentProfile",
    "EditorialCalendar",
    "ContentItem",
    "ContentIdea",
    "MarketingIntegracao",
)


def _backfill_model(apps, model_name, group_fields):
    Model = apps.get_model("marketing", model_name)
    for obj in Model.objects.filter(organization__isnull=True).iterator():
        org_id = organization_id_from_unique_active_membership(obj.usuario_id)
        if org_id is None:
            continue
        obj.organization_id = org_id
        obj.save(update_fields=["organization"])

    if group_fields == ("id",):
        return
    seen = {}
    duplicates = []
    for obj in Model.objects.exclude(organization_id=None).iterator():
        key = tuple(getattr(obj, f) for f in group_fields)
        if key in seen:
            duplicates.append(obj.pk)
            duplicates.append(seen[key])
        else:
            seen[key] = obj.pk
    if duplicates:
        Model.objects.filter(pk__in=set(duplicates)).update(organization_id=None)


def backfill_marketing_organization(apps, schema_editor):
    _backfill_model(apps, "ContentProfile", ("organization_id",))
    _backfill_model(apps, "EditorialCalendar", ("id",))
    _backfill_model(apps, "ContentItem", ("id",))
    _backfill_model(apps, "ContentIdea", ("id",))
    _backfill_model(apps, "MarketingIntegracao", ("organization_id", "plataforma"))


def noop_reverse(apps, schema_editor):
    pass


def _add_org_field(model_name, related_name):
    return migrations.AddField(
        model_name=model_name,
        name="organization",
        field=models.ForeignKey(
            blank=True,
            db_index=True,
            null=True,
            on_delete=django.db.models.deletion.PROTECT,
            related_name=related_name,
            to="organizacoes.organization",
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_rbac_fase13"),
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        _add_org_field("contentprofile", "contentprofile_org_marketing"),
        _add_org_field("editorialcalendar", "editorialcalendar_org_marketing"),
        _add_org_field("contentitem", "contentitem_org_marketing"),
        _add_org_field("contentidea", "contentidea_org_marketing"),
        _add_org_field("marketingintegracao", "marketingintegracao_org_marketing"),
        migrations.RunPython(backfill_marketing_organization, noop_reverse),
        migrations.AddConstraint(
            model_name="contentprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(organization__isnull=False),
                fields=("organization",),
                name="marketing_unique_profile_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketingintegracao",
            constraint=models.UniqueConstraint(
                condition=models.Q(organization__isnull=False),
                fields=("organization", "plataforma"),
                name="marketing_unique_integracao_org_plataforma",
            ),
        ),
    ]
