# Generated by Django 5.2.12 on 2026-09-26 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_organization_owned"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentidea",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_org_marketing",
                to="organizacoes.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contentidea",
            name="usuario",
            field=models.ForeignKey(
                help_text="Criador / compatibilidade legada. Não é o tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_marketing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_org_marketing",
                to="organizacoes.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="usuario",
            field=models.ForeignKey(
                help_text="Criador / compatibilidade legada. Não é o tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_marketing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contentprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_org_marketing",
                to="organizacoes.organization",
            ),
        ),
        migrations.AlterField(
            model_name="contentprofile",
            name="usuario",
            field=models.ForeignKey(
                help_text="Criador / compatibilidade legada. Não é o tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_marketing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="editorialcalendar",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_org_marketing",
                to="organizacoes.organization",
            ),
        ),
        migrations.AlterField(
            model_name="editorialcalendar",
            name="usuario",
            field=models.ForeignKey(
                help_text="Criador / compatibilidade legada. Não é o tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_marketing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="marketingintegracao",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_org_marketing",
                to="organizacoes.organization",
            ),
        ),
        migrations.AlterField(
            model_name="marketingintegracao",
            name="usuario",
            field=models.ForeignKey(
                help_text="Criador / compatibilidade legada. Não é o tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_marketing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
