# Generated by Django 5.2.12 on 2026-10-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_postgres_readiness_state"),
        ("organizacoes", "0002_organizationprovidercredential"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marketingintegracao",
            options={
                "permissions": [
                    ("view_marketing", "Pode visualizar o painel Google Ads"),
                    (
                        "view_resultados_marketing",
                        "Pode visualizar resultados do negócio (analytics)",
                    ),
                    (
                        "view_conteudo_marketing",
                        "Pode visualizar marketing de conteúdo",
                    ),
                    (
                        "edit_conteudo_marketing",
                        "Pode criar e editar conteúdo de marketing",
                    ),
                    (
                        "manage_integracoes_marketing",
                        "Pode gerenciar integrações de marketing",
                    ),
                ],
                "verbose_name": "Integração de marketing",
                "verbose_name_plural": "Integrações de marketing",
            },
        ),
        migrations.CreateModel(
            name="OrganizationGoogleAdsConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disconnected", "Desconectada"),
                            ("authorized", "Autorizada"),
                            ("configured", "Configurada"),
                        ],
                        default="disconnected",
                        max_length=16,
                    ),
                ),
                ("customer_id", models.CharField(blank=True, max_length=32)),
                ("login_customer_id", models.CharField(blank=True, max_length=32)),
                ("descriptive_name", models.CharField(blank=True, max_length=255)),
                ("currency_code", models.CharField(blank=True, max_length=3)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_connection",
                        to="organizacoes.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conexão Google Ads",
                "verbose_name_plural": "Conexões Google Ads",
            },
        ),
    ]
