"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from .database import databases_from_env
from .runtime_env import (
    env_bool,
    env_int,
    parse_csrf_trusted_origins,
    resolve_allowed_hosts,
    resolve_secret_key,
)
from .storage import resolve_default_storage

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# DEV: DJANGO_DEBUG ausente → True. Valor malformado falha (não cai em True).
# STAGING/PROD: DJANGO_DEBUG=false. SECRET_KEY e ALLOWED_HOSTS obrigatórios.
DEBUG = env_bool(os.environ.get("DJANGO_DEBUG"), default=True, name="DJANGO_DEBUG")
SECRET_KEY = resolve_secret_key(
    debug=DEBUG,
    raw=os.environ.get("DJANGO_SECRET_KEY"),
)
ALLOWED_HOSTS = resolve_allowed_hosts(
    debug=DEBUG,
    raw=os.environ.get("DJANGO_ALLOWED_HOSTS"),
)
CSRF_TRUSTED_ORIGINS = parse_csrf_trusted_origins(
    os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS"),
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "usuarios",
    "organizacoes",
    "ia",
    "financeiro",
    "marketing",
    "comercial",
    "django_q",
    "martor",
]

LOGIN_URL = "/usuarios/login/"
LOGIN_REDIRECT_URL = "/"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "organizacoes.middleware.TenantContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "builtins": ["usuarios.templatetags.brnum"],
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "financeiro.context_processors.financeiro_permissoes",
                "marketing.context_processors.marketing_permissoes",
                "comercial.context_processors.comercial_permissoes",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DEV: DATABASE_URL vazio → SQLite local (db.sqlite3).
# STAGING/PROD: injetar DATABASE_URL (postgres/postgresql) externamente.
# Não hardcodar host/user/password. Não commitar .env.

def _db_conn_max_age() -> int:
    raw = (os.environ.get("DB_CONN_MAX_AGE") or "0").strip()
    try:
        return int(raw)
    except ValueError:
        return 0


DATABASES = databases_from_env(
    database_url=os.environ.get("DATABASE_URL", ""),
    sqlite_path=BASE_DIR / "db.sqlite3",
    conn_max_age=_db_conn_max_age(),
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'templates/static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# PREPROD-PRIVATE-STORAGE-01 + OBJECT-STORAGE-P1
# DEV sem S3: FileSystemStorage + MEDIA_ROOT local. NÃO é evidência de segurança.
# Staging/prod: AWS_* completo → storages.backends.s3.S3Storage (privado).
# Config S3 parcial ou DJANGO_OBJECT_STORAGE_REQUIRED sem credenciais → fail-fast.
# Arquivos tenant-owned NÃO podem ser servidos via MEDIA_URL.
# Entrega somente pelo endpoint autorizado usuarios:documento_download.
# Não assumir filesystem persistente de container (Railway).
_static_storage = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)
STORAGES = {
    "default": resolve_default_storage(environ=os.environ),
    "staticfiles": {"BACKEND": _static_storage},
}
SERVE_TENANT_MEDIA = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

from django.contrib.messages import constants

MESSAGE_TAGS = {
    constants.SUCCESS: "border border-emerald-800/80 bg-emerald-950/90 text-emerald-300",
    constants.ERROR: "border border-red-800/80 bg-red-950/90 text-red-300",
    constants.WARNING: "border border-amber-800/80 bg-amber-950/90 text-amber-300",
    constants.INFO: "border border-zinc-700 bg-zinc-900 text-zinc-300",
}

# RAG: PostgreSQL/pgvector é o índice operacional. Sem fallback para LanceDB.
RAG_VECTOR_BACKEND = (os.environ.get("RAG_VECTOR_BACKEND") or "pgvector").strip().lower()
RAG_EMBEDDING_MODEL = "text-embedding-3-small"
RAG_EMBEDDING_DIM = 1536

Q_CLUSTER = {
    "name": os.environ.get("Q_CLUSTER_NAME") or "pythonando",
    "workers": env_int(
        os.environ.get("Q_CLUSTER_WORKERS"), default=1, name="Q_CLUSTER_WORKERS"
    ),
    "retry": env_int(os.environ.get("Q_CLUSTER_RETRY"), default=200, name="Q_CLUSTER_RETRY"),
    "timeout": env_int(
        os.environ.get("Q_CLUSTER_TIMEOUT"), default=180, name="Q_CLUSTER_TIMEOUT"
    ),
    "queue_limit": env_int(
        os.environ.get("Q_CLUSTER_QUEUE_LIMIT"), default=50, name="Q_CLUSTER_QUEUE_LIMIT"
    ),
    "orm": "default",
}

# Railway termina TLS no proxy. HSTS fica para o gate de produção (domínio final).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "{levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.security.DisallowedHost": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

