# Generated by Django 5.2.12 on 2026-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_compromisso_tarefa"),
    ]

    operations = [
        migrations.AddField(
            model_name="compromisso",
            name="data_hora_fim",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
