# Generated by Django 5.2.12 on 2026-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_cliente_status_opcoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="fase_funil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primeiro_contato", "Primeiro contato"),
                    ("proposta_enviada", "Proposta enviada"),
                    ("aguardando_decisao", "Aguardando decisão"),
                    ("novo_contato", "Novo contato"),
                ],
                default="primeiro_contato",
                max_length=25,
            ),
        ),
    ]
