# Generated by Django 5.2.12 on 2026-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_cliente_fase_funil"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="data_relatorio_prospeccao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="relatorio_prospeccao",
            field=models.TextField(blank=True),
        ),
    ]
