# Generated by Django 5.2.12 on 2026-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0007_cliente_data_relatorio_prospeccao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
