# Generated by Django 5.2.12 on 2026-08-22 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_dados_agenda(apps, schema_editor):
    Tarefa = apps.get_model("usuarios", "Tarefa")
    Compromisso = apps.get_model("usuarios", "Compromisso")
    Tarefa.objects.filter(concluida=True).update(status="concluida")
    for c in Compromisso.objects.filter(responsavel__isnull=True):
        c.responsavel_id = c.user_id
        c.save(update_fields=["responsavel_id"])
    for t in Tarefa.objects.filter(responsavel__isnull=True):
        t.responsavel_id = t.user_id
        t.save(update_fields=["responsavel_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_cliente_endereco_cliente_telefone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_tipo",
                    models.CharField(
                        choices=[("compromisso", "Compromisso"), ("tarefa", "Tarefa")],
                        max_length=20,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criado", "Criado"),
                            ("alterado", "Alterado"),
                            ("cancelado", "Cancelado"),
                            ("concluido", "Concluído"),
                            ("responsavel_alterado", "Responsável alterado"),
                            ("prazo_alterado", "Prazo alterado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("campo", models.CharField(blank=True, max_length=60)),
                ("valor_anterior", models.TextField(blank=True)),
                ("valor_novo", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="CompromissoParticipante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="tarefa",
            options={"ordering": ["status", "prazo", "criado_em"]},
        ),
        migrations.AddField(
            model_name="compromisso",
            name="area_juridica",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="cancelado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compromissos",
                to="usuarios.cliente",
            ),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="lembrete_minutos",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="metadados",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="motivo_cancelamento",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="prazo_interno",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="prazo_oficial",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("normal", "Normal"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="processo_referencia",
            field=models.CharField(
                blank=True,
                help_text="Número CNJ ou referência do processo (até existir model dedicado).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="recorrencia",
            field=models.CharField(
                choices=[
                    ("nao_repetir", "Não repetir"),
                    ("semanal", "Semanal"),
                    ("quinzenal", "Quinzenal"),
                    ("mensal", "Mensal"),
                ],
                default="nao_repetir",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compromissos_responsavel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="status",
            field=models.CharField(
                choices=[
                    ("agendado", "Agendado"),
                    ("confirmado", "Confirmado"),
                    ("realizado", "Realizado"),
                    ("nao_compareceu", "Não compareceu"),
                    ("cancelado", "Cancelado"),
                ],
                default="agendado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="compromisso",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("consulta", "Consulta"),
                    ("reuniao", "Reunião"),
                    ("audiencia", "Audiência"),
                    ("prazo", "Prazo"),
                    ("diligencia", "Diligência"),
                    ("retorno_cliente", "Retorno ao cliente"),
                    ("followup_comercial", "Follow-up comercial"),
                    ("interno", "Interno"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarefas",
                to="usuarios.cliente",
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("normal", "Normal"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="processo_referencia",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarefas_responsavel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_andamento", "Em andamento"),
                    ("concluida", "Concluída"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(
                fields=["user", "data_hora"], name="usuarios_co_user_id_aafb20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(
                fields=["user", "status"], name="usuarios_co_user_id_4311b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(
                fields=["user", "tipo"], name="usuarios_co_user_id_ef15bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(
                fields=["responsavel", "data_hora"],
                name="usuarios_co_respons_178c77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(
                fields=["cliente"], name="usuarios_co_cliente_7e0314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(
                fields=["user", "status"], name="usuarios_ta_user_id_16bad3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(
                fields=["user", "prazo"], name="usuarios_ta_user_id_b31d3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(
                fields=["responsavel", "prazo"], name="usuarios_ta_respons_30c461_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(
                fields=["cliente"], name="usuarios_ta_cliente_e19cff_idx"
            ),
        ),
        migrations.AddField(
            model_name="agendaauditlog",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agenda_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compromissoparticipante",
            name="compromisso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participantes",
                to="usuarios.compromisso",
            ),
        ),
        migrations.AddField(
            model_name="compromissoparticipante",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compromissos_participante",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="agendaauditlog",
            index=models.Index(
                fields=["item_tipo", "item_id"], name="usuarios_ag_item_ti_381947_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendaauditlog",
            index=models.Index(
                fields=["usuario", "criado_em"], name="usuarios_ag_usuario_307f1f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="compromissoparticipante",
            constraint=models.UniqueConstraint(
                fields=("compromisso", "usuario"),
                name="usuarios_unique_participante_compromisso",
            ),
        ),
        migrations.RunPython(migrar_dados_agenda, migrations.RunPython.noop),
    ]
