# Generated by Django 5.2.12 on 2026-08-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_agenda_fase10_lembretes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="agendalembrete",
            new_name="usuarios_ag_user_id_9ff9bc_idx",
            old_name="usuarios_ag_user_id_6f8a2d_idx",
        ),
    ]
