# Generated by Django 5.2.12 on 2026-08-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0011_cobranca_fase1"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="metadados",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="compromisso",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("consulta", "Consulta"),
                    ("reuniao", "Reunião"),
                    ("audiencia", "Audiência"),
                    ("prazo", "Prazo"),
                    ("diligencia", "Diligência"),
                    ("retorno_cliente", "Retorno ao cliente"),
                    ("followup_comercial", "Follow-up comercial"),
                    ("cobranca", "Cobrança"),
                    ("interno", "Interno"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=30,
            ),
        ),
    ]
