# Generated by Django 5.2.12 on 2026-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0016_mkt_perf_fase14"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compromisso",
            options={"ordering": ["data_hora"]},
        ),
        migrations.RenameIndex(
            model_name="cliente",
            new_name="usuarios_cl_user_id_318ff1_idx",
            old_name="usuarios_cl_user_id_origem_idx",
        ),
        migrations.RenameIndex(
            model_name="cliente",
            new_name="usuarios_cl_user_id_3b1e2a_idx",
            old_name="usuarios_cl_user_atrib_orig_idx",
        ),
        migrations.RenameIndex(
            model_name="compromisso",
            new_name="usuarios_co_user_id_292446_idx",
            old_name="usuarios_co_user_id_6a8f2d_idx",
        ),
        migrations.RenameIndex(
            model_name="compromisso",
            new_name="usuarios_co_user_id_240c04_idx",
            old_name="usuarios_co_user_id_9c4e1a_idx",
        ),
        migrations.AlterField(
            model_name="compromisso",
            name="origem_lead",
            field=models.CharField(
                blank=True,
                choices=[
                    ("indicacao", "Indicação"),
                    ("site", "Site"),
                    ("redes_sociais", "Redes sociais"),
                    ("telefone", "Telefone"),
                    ("google_ads", "Google Ads"),
                    ("outro", "Outro"),
                ],
                default="",
                help_text="Origem do lead para consultas.",
                max_length=30,
            ),
        ),
    ]
