# Generated by Django 5.2.12 on 2026-09-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0001_initial"),
        ("usuarios", "0017_fase2_acoes_resolvidas"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes",
                to="organizacoes.organization",
            ),
        ),
    ]
