# Generated by Django 5.2.12 on 2026-10-08 19:18

import usuarios.services.document_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0020_restore_agenda_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentos",
            name="arquivo",
            field=models.FileField(
                upload_to=usuarios.services.document_storage.documento_upload_to
            ),
        ),
    ]
