# Generated by Django 5.2.12 on 2026-08-27 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComercialAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("meta_criada", "Meta criada"),
                            ("meta_alterada", "Meta alterada"),
                            ("ticket_manual", "Ticket médio ajustado manualmente"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("detalhe", models.TextField(blank=True)),
                (
                    "criado_em",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "ator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comercial_acoes_auditadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Tenant / escritório dono do dado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comercial_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria comercial",
                "verbose_name_plural": "Auditorias comerciais",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "criado_em"],
                        name="comercial_c_usuario_65f04b_idx",
                    ),
                    models.Index(
                        fields=["usuario", "acao"],
                        name="comercial_c_usuario_de1d1d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetaComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField(db_index=True)),
                ("meta_anual", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "meta_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Se vazio no formulário, deriva de meta_anual / 12.",
                        max_digits=14,
                    ),
                ),
                (
                    "ticket_medio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ticket usado no cálculo reverso. Null = usar automático.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "ticket_medio_manual",
                    models.BooleanField(
                        default=False,
                        help_text="True quando o usuário sobrescreveu o ticket automático.",
                    ),
                ),
                ("vigencia_inicio", models.DateField()),
                ("vigencia_fim", models.DateField()),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metas_comerciais_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas_comerciais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta comercial",
                "verbose_name_plural": "Metas comerciais",
                "ordering": ["-ano", "-atualizado_em"],
                "permissions": [
                    ("view_dashboard", "Pode visualizar o painel comercial"),
                    ("manage_goals", "Pode criar e editar metas comerciais"),
                    ("view_revenue", "Pode visualizar faturamento e gaps"),
                    ("view_team", "Pode visualizar desempenho da equipe"),
                    ("export_reports", "Pode exportar relatórios comerciais"),
                ],
                "indexes": [
                    models.Index(
                        fields=["usuario", "ano"], name="comercial_m_usuario_868787_idx"
                    ),
                    models.Index(
                        fields=["usuario", "vigencia_inicio", "vigencia_fim"],
                        name="comercial_m_usuario_9a511a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "ano"),
                        name="uniq_comercial_meta_usuario_ano",
                    )
                ],
            },
        ),
    ]
