# Generated by Django 5.2.12 on 2026-08-27 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0002_rbac_fase1"),
        ("usuarios", "0017_fase2_acoes_resolvidas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comercialauditlog",
            name="acao",
            field=models.CharField(
                choices=[
                    ("meta_criada", "Meta criada"),
                    ("meta_alterada", "Meta alterada"),
                    ("ticket_manual", "Ticket médio ajustado manualmente"),
                    ("acao_resolvida", "Ação comercial marcada como resolvida"),
                    ("tarefa_criada", "Tarefa criada a partir do Comercial"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="AcaoComercialResolvida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador estável tipo:proposta_sem_followup:123",
                        max_length=120,
                    ),
                ),
                (
                    "resolvido_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes_comerciais_resolvidas",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "resolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_comerciais_marcadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes_comerciais_resolvidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação comercial resolvida",
                "verbose_name_plural": "Ações comerciais resolvidas",
                "ordering": ["-resolvido_em"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "resolvido_em"],
                        name="comercial_a_usuario_182335_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "chave"),
                        name="uniq_comercial_acao_resolvida_usuario_chave",
                    )
                ],
            },
        ),
    ]
