# Generated by Django 5.2.12 on 2026-08-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0003_fase2_acoes_resolvidas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvGrowthScoreSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ref", models.DateField(db_index=True)),
                ("score", models.PositiveSmallIntegerField()),
                ("aquisicao", models.PositiveSmallIntegerField()),
                ("atendimento", models.PositiveSmallIntegerField()),
                ("conversao", models.PositiveSmallIntegerField()),
                ("gestao", models.PositiveSmallIntegerField()),
                ("financeiro", models.PositiveSmallIntegerField()),
                ("dados", models.PositiveSmallIntegerField()),
                ("detalhe", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adv_growth_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ADV Growth Score",
                "verbose_name_plural": "ADV Growth Scores",
                "ordering": ["-data_ref"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "data_ref"],
                        name="comercial_a_usuario_08dcd5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "data_ref"),
                        name="uniq_comercial_adv_score_usuario_data",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestimentoMidia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "canal",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: google_ads, instagram, etc. Vazio = geral.",
                        max_length=40,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investimentos_midia_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investimentos_midia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Investimento de mídia",
                "verbose_name_plural": "Investimentos de mídia",
                "ordering": ["-data_fim", "-id"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "data_inicio", "data_fim"],
                        name="comercial_i_usuario_474d18_idx",
                    )
                ],
            },
        ),
    ]
