# Generated by Django 5.2.12

import django.db.models.deletion
from django.db import migrations, models

from organizacoes.backfill import organization_id_from_unique_active_membership


def _backfill_and_clear_duplicates(apps, model_name, user_field, group_fields):
    Model = apps.get_model("comercial", model_name)
    for obj in Model.objects.filter(organization__isnull=True).iterator():
        user_id = getattr(obj, f"{user_field}_id", None)
        org_id = organization_id_from_unique_active_membership(user_id)
        if org_id is None:
            continue
        obj.organization_id = org_id
        obj.save(update_fields=["organization"])

    seen = {}
    duplicates = []
    for obj in Model.objects.exclude(organization_id=None).iterator():
        key = tuple(getattr(obj, f) for f in group_fields)
        if key in seen:
            duplicates.append(obj.pk)
            duplicates.append(seen[key])
        else:
            seen[key] = obj.pk
    if duplicates:
        Model.objects.filter(pk__in=set(duplicates)).update(organization_id=None)


def backfill_comercial_organization(apps, schema_editor):
    _backfill_and_clear_duplicates(
        apps, "MetaComercial", "usuario", ("organization_id", "ano")
    )
    _backfill_and_clear_duplicates(
        apps, "InvestimentoMidia", "usuario", ("id",)
    )
    _backfill_and_clear_duplicates(
        apps,
        "AcaoComercialResolvida",
        "usuario",
        ("organization_id", "chave"),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0004_fase3_score_investimento"),
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metacomercial",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metas_comerciais",
                to="organizacoes.organization",
            ),
        ),
        migrations.AddField(
            model_name="investimentomidia",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investimentos_midia",
                to="organizacoes.organization",
            ),
        ),
        migrations.AddField(
            model_name="acaocomercialresolvida",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acoes_comerciais_resolvidas",
                to="organizacoes.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="metacomercial",
            index=models.Index(
                fields=["organization", "ano"],
                name="comercial_m_organiz_meta_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="acaocomercialresolvida",
            index=models.Index(
                fields=["organization", "resolvido_em"],
                name="comercial_a_organiz_res_idx",
            ),
        ),
        migrations.RunPython(backfill_comercial_organization, noop_reverse),
        migrations.AddConstraint(
            model_name="metacomercial",
            constraint=models.UniqueConstraint(
                condition=models.Q(organization__isnull=False),
                fields=("organization", "ano"),
                name="uniq_comercial_meta_org_ano",
            ),
        ),
        migrations.AddConstraint(
            model_name="acaocomercialresolvida",
            constraint=models.UniqueConstraint(
                condition=models.Q(organization__isnull=False),
                fields=("organization", "chave"),
                name="uniq_comercial_acao_resolvida_org_chave",
            ),
        ),
    ]
