# Generated by Django 5.2.12 on 2026-09-26 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0005_organization_owned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="acaocomercialresolvida",
            name="usuario",
            field=models.ForeignKey(
                help_text="Ator que resolveu / compatibilidade legada. Não é o tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acoes_comerciais_resolvidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="investimentomidia",
            name="usuario",
            field=models.ForeignKey(
                help_text="Criador / compatibilidade legada. Não é o tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investimentos_midia",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="metacomercial",
            name="usuario",
            field=models.ForeignKey(
                help_text="Criador / compatibilidade legada. Não é o tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metas_comerciais",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
