# Generated by Django 5.2.12 on 2026-05-17 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banco",
            name="saldo_inicial",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
    ]
