# Generated by Django 5.2.12 on 2026-08-22 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_banco_saldo_inicial_blank"),
        ("usuarios", "0011_cobranca_fase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cobranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contrato_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Referência do contrato até existir model dedicado (Fase 6).",
                        max_length=64,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                (
                    "valor_original",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("data_vencimento", models.DateField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("honorarios", "Honorários"),
                            ("consultoria", "Consultoria"),
                            ("mensalidade", "Mensalidade"),
                            ("exito", "Êxito"),
                            ("custas", "Custas reembolsáveis"),
                            ("outro", "Outro"),
                        ],
                        default="honorarios",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("pending", "A vencer"),
                            ("due_soon", "Vence em breve"),
                            ("overdue", "Vencido"),
                            ("paid", "Recebido"),
                            ("partially_paid", "Parcialmente recebido"),
                            ("canceled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "forma_prevista_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "Pix"),
                            ("boleto", "Boleto"),
                            ("transferencia", "Transferência"),
                            ("cartao", "Cartão"),
                            ("dinheiro", "Dinheiro"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacoes_internas", models.TextField(blank=True)),
                (
                    "grupo_parcelamento_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "parcela_numero",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "parcela_total",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_cancelamento", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobrancas",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cobrancas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cobrancas_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cobrancas_financeiro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cobrança",
                "verbose_name_plural": "Cobranças",
                "ordering": ["data_vencimento", "id"],
            },
        ),
        migrations.CreateModel(
            name="CobrancaHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criada", "Cobrança criada"),
                            ("editada", "Cobrança editada"),
                            ("cancelada", "Cobrança cancelada"),
                            ("vencimento_alterado", "Vencimento alterado"),
                            ("responsavel_alterado", "Responsável alterado"),
                            ("recebimento_registrado", "Recebimento registrado"),
                            ("recebimento_estornado", "Recebimento estornado"),
                            ("status_alterado", "Status alterado"),
                            ("vencida", "Cobrança vencida"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("metadados", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_historico_cobranca",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cobranca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="financeiro.cobranca",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_cobrancas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de cobrança",
                "verbose_name_plural": "Históricos de cobrança",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="CobrancaRecebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("data_recebimento", models.DateField()),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("pix", "Pix"),
                            ("boleto", "Boleto"),
                            ("transferencia", "Transferência"),
                            ("cartao", "Cartão"),
                            ("dinheiro", "Dinheiro"),
                            ("outro", "Outro"),
                        ],
                        default="pix",
                        max_length=20,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=120)),
                ("observacao", models.TextField(blank=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_estorno", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cobranca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recebimentos",
                        to="financeiro.cobranca",
                    ),
                ),
                (
                    "movimento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vínculo opcional com receita realizada no extrato.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recebimentos_cobranca",
                        to="financeiro.movimento",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recebimentos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recebimentos_cobranca",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebimento de cobrança",
                "verbose_name_plural": "Recebimentos de cobrança",
                "ordering": ["-data_recebimento", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="cobranca",
            index=models.Index(
                fields=["usuario", "status", "data_vencimento"],
                name="financeiro__usuario_5ff1f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cobranca",
            index=models.Index(
                fields=["usuario", "cliente"], name="financeiro__usuario_f58601_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cobranca",
            index=models.Index(
                fields=["usuario", "data_vencimento"],
                name="financeiro__usuario_9475c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cobranca",
            index=models.Index(
                fields=["responsavel", "data_vencimento"],
                name="financeiro__respons_23ea4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cobrancahistorico",
            index=models.Index(
                fields=["cobranca", "criado_em"], name="financeiro__cobranc_200b2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cobrancahistorico",
            index=models.Index(
                fields=["usuario", "criado_em"], name="financeiro__usuario_ec2b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cobrancarecebimento",
            index=models.Index(
                fields=["usuario", "data_recebimento"],
                name="financeiro__usuario_8d7562_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cobrancarecebimento",
            index=models.Index(
                fields=["cobranca", "cancelado_em"],
                name="financeiro__cobranc_06fa44_idx",
            ),
        ),
    ]
