# Generated by Django 5.2.12 on 2026-08-22 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_cobranca_fase1"),
        ("usuarios", "0011_cobranca_fase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cobranca",
            name="contrato_referencia",
            field=models.CharField(
                blank=True,
                help_text="Cópia da referência do contrato para exibição e busca.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="cobrancahistorico",
            name="acao",
            field=models.CharField(
                choices=[
                    ("criada", "Cobrança criada"),
                    ("editada", "Cobrança editada"),
                    ("cancelada", "Cobrança cancelada"),
                    ("vencimento_alterado", "Vencimento alterado"),
                    ("responsavel_alterado", "Responsável alterado"),
                    ("recebimento_registrado", "Recebimento registrado"),
                    ("recebimento_estornado", "Recebimento estornado"),
                    ("parcelamento_criado", "Parcelamento criado"),
                    ("cobrancas_geradas_contrato", "Cobranças geradas do contrato"),
                    ("status_alterado", "Status alterado"),
                    ("vencida", "Cobrança vencida"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia", models.CharField(max_length=64)),
                ("descricao", models.CharField(max_length=255)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativo"),
                            ("closed", "Encerrado"),
                            ("canceled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos_financeiro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="cobranca",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cobrancas",
                to="financeiro.contrato",
            ),
        ),
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["usuario", "cliente"], name="financeiro__usuario_af5985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["usuario", "status"], name="financeiro__usuario_547f51_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.UniqueConstraint(
                fields=("usuario", "referencia"),
                name="uniq_financeiro_contrato_usuario_referencia",
            ),
        ),
    ]
