# Generated by Django 5.2.12 on 2026-08-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_contrato_fase6"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cobrancahistorico",
            name="acao",
            field=models.CharField(
                choices=[
                    ("criada", "Cobrança criada"),
                    ("editada", "Cobrança editada"),
                    ("cancelada", "Cobrança cancelada"),
                    ("vencimento_alterado", "Vencimento alterado"),
                    ("responsavel_alterado", "Responsável alterado"),
                    ("recebimento_registrado", "Recebimento registrado"),
                    ("recebimento_estornado", "Recebimento estornado"),
                    ("parcelamento_criado", "Parcelamento criado"),
                    ("agenda_vinculada", "Vinculada à agenda"),
                    ("cobrancas_geradas_contrato", "Cobranças geradas do contrato"),
                    ("status_alterado", "Status alterado"),
                    ("vencida", "Cobrança vencida"),
                ],
                max_length=30,
            ),
        ),
    ]
