# Generated by Django 5.2.12 on 2026-10-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProviderCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google_ads", "Google Ads"), ("asaas", "Asaas")],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inativa"),
                            ("configured", "Configurada"),
                        ],
                        default="inactive",
                        max_length=16,
                    ),
                ),
                ("ciphertext", models.BinaryField()),
                ("key_id", models.CharField(default="v1", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_credentials",
                        to="organizacoes.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credencial de provider",
                "verbose_name_plural": "Credenciais de provider",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "provider"),
                        name="uniq_org_provider_credential",
                    )
                ],
            },
        ),
    ]
